import = ["~/dotfiles/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "Menlo", style = "Italic" }
size = 14
offset = { y = 7 } 

[window]
# option_as_alt = "Both"
