import = ["~/dotfiles/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "Menlo", style = "Italic" }
size = 14
offset = { y = 7 } 

[window]
option_as_alt = "Both"

# [keyboard]
# bindings = [
#   { key = "Left",  mods = "Alt",     chars = "\u001bB"   },
#   { key = "Right", mods = "Alt",     chars = "\u001bF"   },
#   { key = "Back",  mods = "Command", chars = "\u0015"    },
# ]

# [[keyboard.bindings]]
# key = "Back"
# mods = "Command"
# chars = "\u0015"
#
# [[keyboard.bindings]]
# key = "Right"
# mods = "Alt"
# chars = "\u001BF"
#
# [[keyboard.bindings]]
# key = "Left"
# mods = "Alt"
# chars = "\u001BB"


