return {
  require("plugins.code.comment"),
  require("plugins.code.conform"),
  require("plugins.code.treesitter"),
  require("plugins.code.lsp"),
  require("plugins.code.autopairs"),
  require("plugins.code.copilot"),
  require("plugins.code.luasnip"),
  require("plugins.code.nvim-cmp"),
  require("plugins.code.go"),
  -- require("plugins.code.indent-blankline"),
  require("plugins.code.vim-doge"),
  require("plugins.code.mini-move"),
  require("plugins.code.vim-visual-multi"),
  require("plugins.code.rainbow-delimiters"),
  require("plugins.code.yanky"),
  require("plugins.code.vim-illuminate"),
  require("plugins.code.nvim-surround"),
  require("plugins.code.neotest"),
  require("plugins.code.smartyank"),
  require("plugins.code.substitute"),
}
